### ISSUE TITLE
Application launcher and auto-start

### ISSUE THREAD

**Issue by flossgeek** [ilpianista/harbour-Tailscale#2]
The application doesn't work when starting it from the application launcher. It needs to be started from a terminal after every boot. It would especially be nice if the app would auto-start on every boot.

**Comment by flossgeek** [comment]
Thanks for resolving this issue so fast!
The service seems to auto-start now, but whenever I open the interface via the application launcher, it does not seem to know that it already started. So all I get is "unexpected state: NoState". I also can't put the link down or up from within the interface.

**Comment by ilpianista** [comment]
@flossgeek Hi, unfortunately I cannot reproduce this in the emulator :disappointed:

I cannot fix this until I get the new display for my phone, sorry. Please open a new issue to track this properly. Thanks!
