### ISSUE TITLE
(Magic)DNS Support

### ISSUE THREAD

**Issue by flossgeek** [ilpianista/harbour-Tailscale#3]
Tailscale has a feature so that every device on the tailnet is reachable by it's unique name instead of the IP address. From my SFOS phone, however, I can't reach my machines as I can on my other devices with tailscale installed. Is this an issue that can be fixed within this application or does it have something to do with the core sailfish system?
Thanks!

**Comment by ilpianista** [comment]
It works here. Did you modify `/etc/resolv.conf` in someway?

**Comment by flossgeek** [comment]
No, the contents of `/etc/resolv.conf` look like this for me:
```
nameserver 100.100.100.100
search <subdomain>
```
